name: Generate Cosmic Globe Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate cosmic globe
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/cosmic-globe.svg
            dist/cosmic-globe-dark.svg?palette=github-dark
            dist/cosmic-globe.gif?color_snake=orange&color_dots=#bfd6f6,#8cc8ff,#64b5f6,#42a5f5,#2196f3

      - name: Create Spinning Globe SVG
        run: |
          mkdir -p dist
          cat > dist/spinning-globe.svg << 'EOF'
          <svg width="800" height="400" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <radialGradient id="earthGradient" cx="30%" cy="30%">
                <stop offset="0%" style="stop-color:#87CEEB;stop-opacity:1" />
                <stop offset="70%" style="stop-color:#4682B4;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#191970;stop-opacity:1" />
              </radialGradient>
              <radialGradient id="spaceGradient" cx="50%" cy="50%">
                <stop offset="0%" style="stop-color:#000428;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#004e92;stop-opacity:1" />
              </radialGradient>
              <filter id="glow">
                <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
                <feMerge> 
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            
            <!-- Space Background -->
            <rect width="800" height="400" fill="url(#spaceGradient)"/>
            
            <!-- Stars -->
            <circle cx="100" cy="50" r="1" fill="white" opacity="0.8">
              <animate attributeName="opacity" values="0.3;1;0.3" dur="3s" repeatCount="indefinite"/>
            </circle>
            <circle cx="200" cy="80" r="1.5" fill="white" opacity="0.6">
              <animate attributeName="opacity" values="0.2;0.9;0.2" dur="4s" repeatCount="indefinite"/>
            </circle>
            <circle cx="150" cy="120" r="1" fill="white" opacity="0.7">
              <animate attributeName="opacity" values="0.4;1;0.4" dur="2.5s" repeatCount="indefinite"/>
            </circle>
            <circle cx="300" cy="60" r="1" fill="white" opacity="0.5">
              <animate attributeName="opacity" values="0.3;0.8;0.3" dur="3.5s" repeatCount="indefinite"/>
            </circle>
            <circle cx="250" cy="150" r="1.2" fill="white" opacity="0.8">
              <animate attributeName="opacity" values="0.2;1;0.2" dur="2.8s" repeatCount="indefinite"/>
            </circle>
            <circle cx="350" cy="100" r="1" fill="white" opacity="0.6">
              <animate attributeName="opacity" values="0.4;0.9;0.4" dur="4.2s" repeatCount="indefinite"/>
            </circle>
            <circle cx="450" cy="70" r="1.3" fill="white" opacity="0.7">
              <animate attributeName="opacity" values="0.3;1;0.3" dur="3.8s" repeatCount="indefinite"/>
            </circle>
            <circle cx="500" cy="130" r="1" fill="white" opacity="0.5">
              <animate attributeName="opacity" values="0.2;0.8;0.2" dur="2.2s" repeatCount="indefinite"/>
            </circle>
            <circle cx="600" cy="90" r="1.4" fill="white" opacity="0.9">
              <animate attributeName="opacity" values="0.4;1;0.4" dur="3.2s" repeatCount="indefinite"/>
            </circle>
            <circle cx="650" cy="160" r="1" fill="white" opacity="0.6">
              <animate attributeName="opacity" values="0.3;0.9;0.3" dur="4.5s" repeatCount="indefinite"/>
            </circle>
            
            <!-- Spinning Globe -->
            <g transform="translate(400,200)">
              <!-- Globe Shadow -->
              <ellipse cx="0" cy="60" rx="80" ry="15" fill="rgba(0,0,0,0.3)"/>
              
              <!-- Main Globe -->
              <circle cx="0" cy="0" r="70" fill="url(#earthGradient)" filter="url(#glow)">
                <animateTransform attributeName="transform" type="rotate" 
                  values="0;360" dur="10s" repeatCount="indefinite"/>
              </circle>
              
              <!-- Continents (simplified) -->
              <g>
                <animateTransform attributeName="transform" type="rotate" 
                  values="0;360" dur="10s" repeatCount="indefinite"/>
                
                <!-- Africa/Europe -->
                <path d="M -10,-50 Q 0,-40 10,-30 Q 15,-20 8,-10 Q 5,0 -5,10 Q -15,5 -20,-10 Q -15,-30 -10,-50" 
                      fill="#228B22" opacity="0.8"/>
                
                <!-- Asia -->
                <path d="M 20,-45 Q 40,-35 50,-20 Q 45,-5 35,10 Q 25,15 15,5 Q 20,-15 20,-45" 
                      fill="#228B22" opacity="0.8"/>
                
                <!-- Americas -->
                <path d="M -50,-30 Q -40,-20 -35,-5 Q -40,10 -50,20 Q -55,5 -60,-15 Q -55,-25 -50,-30" 
                      fill="#228B22" opacity="0.8"/>
              </g>
              
              <!-- Atmosphere Glow -->
              <circle cx="0" cy="0" r="75" fill="none" stroke="#87CEEB" stroke-width="2" opacity="0.6">
                <animate attributeName="opacity" values="0.3;0.8;0.3" dur="4s" repeatCount="indefinite"/>
              </circle>
              
              <!-- Orbital Ring -->
              <ellipse cx="0" cy="0" rx="120" ry="30" fill="none" stroke="rgba(255,255,255,0.3)" stroke-width="1">
                <animateTransform attributeName="transform" type="rotate" 
                  values="0;360" dur="20s" repeatCount="indefinite"/>
              </ellipse>
              
              <!-- Satellite -->
              <g>
                <animateTransform attributeName="transform" type="rotate" 
                  values="0;360" dur="8s" repeatCount="indefinite"/>
                <circle cx="100" cy="0" r="3" fill="#FFD700">
                  <animate attributeName="r" values="2;4;2" dur="2s" repeatCount="indefinite"/>
                </circle>
              </g>
            </g>
            
            <!-- Text -->
            <text x="400" y="350" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="16" opacity="0.8">
              🚀 Machine Learning Engineer • Exploring the Data Universe 🌌
            </text>
            
            <!-- GitHub Activity Representation -->
            <g transform="translate(50, 320)">
              <text x="0" y="0" fill="white" font-family="Arial, sans-serif" font-size="12" opacity="0.7">
                GitHub Activity:
              </text>
              
              <!-- Activity bars representing commits -->
              <rect x="120" y="-8" width="3" height="8" fill="#00ff87">
                <animate attributeName="height" values="4;12;4" dur="2s" repeatCount="indefinite" begin="0s"/>
              </rect>
              <rect x="125" y="-6" width="3" height="6" fill="#00ff87">
                <animate attributeName="height" values="3;10;3" dur="2s" repeatCount="indefinite" begin="0.2s"/>
              </rect>
              <rect x="130" y="-10" width="3" height="10" fill="#00ff87">
                <animate attributeName="height" values="5;15;5" dur="2s" repeatCount="indefinite" begin="0.4s"/>
              </rect>
              <rect x="135" y="-7" width="3" height="7" fill="#00ff87">
                <animate attributeName="height" values="4;11;4" dur="2s" repeatCount="indefinite" begin="0.6s"/>
              </rect>
              <rect x="140" y="-9" width="3" height="9" fill="#00ff87">
                <animate attributeName="height" values="6;13;6" dur="2s" repeatCount="indefinite" begin="0.8s"/>
              </rect>
            </g>
          </svg>
          EOF

      - name: Create Galaxy Spiral Animation
        run: |
          cat > dist/galaxy-spiral.svg << 'EOF'
          <svg width="800" height="400" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <radialGradient id="galaxyCenter" cx="50%" cy="50%">
                <stop offset="0%" style="stop-color:#FFD700;stop-opacity:1" />
                <stop offset="30%" style="stop-color:#FF6347;stop-opacity:0.8" />
                <stop offset="70%" style="stop-color:#4169E1;stop-opacity:0.6" />
                <stop offset="100%" style="stop-color:#191970;stop-opacity:0.3" />
              </radialGradient>
              <radialGradient id="deepSpace" cx="50%" cy="50%">
                <stop offset="0%" style="stop-color:#0c0c0c;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#1a1a2e;stop-opacity:1" />
              </radialGradient>
              <filter id="starGlow">
                <feGaussianBlur stdDeviation="2" result="coloredBlur"/>
                <feMerge> 
                  <feMergeNode in="coloredBlur"/>
                  <feMergeNode in="SourceGraphic"/>
                </feMerge>
              </filter>
            </defs>
            
            <!-- Deep Space Background -->
            <rect width="800" height="400" fill="url(#deepSpace)"/>
            
            <!-- Galaxy Center -->
            <circle cx="400" cy="200" r="40" fill="url(#galaxyCenter)" filter="url(#starGlow)">
              <animate attributeName="r" values="35;45;35" dur="6s" repeatCount="indefinite"/>
            </circle>
            
            <!-- Spiral Arms -->
            <g transform="translate(400,200)">
              <animateTransform attributeName="transform" type="rotate" 
                values="0 400 200;360 400 200" dur="30s" repeatCount="indefinite"/>
              
              <!-- First Spiral Arm -->
              <path d="M 0,0 Q 50,-30 100,-20 Q 150,-10 200,10 Q 250,30 280,60" 
                    stroke="#4169E1" stroke-width="3" fill="none" opacity="0.7">
                <animate attributeName="opacity" values="0.4;0.9;0.4" dur="4s" repeatCount="indefinite"/>
              </path>
              
              <!-- Second Spiral Arm -->
              <path d="M 0,0 Q -50,30 -100,20 Q -150,10 -200,-10 Q -250,-30 -280,-60" 
                    stroke="#4169E1" stroke-width="3" fill="none" opacity="0.7">
                <animate attributeName="opacity" values="0.4;0.9;0.4" dur="4s" repeatCount="indefinite" begin="2s"/>
              </path>
              
              <!-- Third Spiral Arm -->
              <path d="M 0,0 Q 30,50 20,100 Q 10,150 -10,200 Q -30,250 -60,280" 
                    stroke="#4169E1" stroke-width="3" fill="none" opacity="0.7">
                <animate attributeName="opacity" values="0.4;0.9;0.4" dur="4s" repeatCount="indefinite" begin="1s"/>
              </path>
              
              <!-- Fourth Spiral Arm -->
              <path d="M 0,0 Q -30,-50 -20,-100 Q -10,-150 10,-200 Q 30,-250 60,-280" 
                    stroke="#4169E1" stroke-width="3" fill="none" opacity="0.7">
                <animate attributeName="opacity" values="0.4;0.9;0.4" dur="4s" repeatCount="indefinite" begin="3s"/>
              </path>
              
              <!-- Stars along spiral arms -->
              <circle cx="80" cy="-15" r="2" fill="#FFD700">
                <animate attributeName="opacity" values="0.3;1;0.3" dur="3s" repeatCount="indefinite"/>
              </circle>
              <circle cx="150" cy="5" r="1.5" fill="#87CEEB">
                <animate attributeName="opacity" values="0.2;0.8;0.2" dur="4s" repeatCount="indefinite"/>
              </circle>
              <circle cx="-120" cy="15" r="2" fill="#FFD700">
                <animate attributeName="opacity" values="0.4;1;0.4" dur="2.5s" repeatCount="indefinite"/>
              </circle>
              <circle cx="15" cy="80" r="1.8" fill="#87CEEB">
                <animate attributeName="opacity" values="0.3;0.9;0.3" dur="3.5s" repeatCount="indefinite"/>
              </circle>
            </g>
            
            <!-- Distant Stars -->
            <circle cx="100" cy="50" r="1" fill="white" opacity="0.6">
              <animate attributeName="opacity" values="0.2;0.8;0.2" dur="5s" repeatCount="indefinite"/>
            </circle>
            <circle cx="700" cy="80" r="1.5" fill="white" opacity="0.7">
              <animate attributeName="opacity" values="0.3;1;0.3" dur="4s" repeatCount="indefinite"/>
            </circle>
            <circle cx="150" cy="350" r="1" fill="white" opacity="0.5">
              <animate attributeName="opacity" values="0.1;0.7;0.1" dur="6s" repeatCount="indefinite"/>
            </circle>
            <circle cx="650" cy="320" r="1.2" fill="white" opacity="0.8">
              <animate attributeName="opacity" values="0.4;1;0.4" dur="3s" repeatCount="indefinite"/>
            </circle>
            
            <!-- Nebula Effect -->
            <ellipse cx="600" cy="100" rx="40" ry="20" fill="rgba(255,20,147,0.3)">
              <animate attributeName="opacity" values="0.2;0.5;0.2" dur="8s" repeatCount="indefinite"/>
            </ellipse>
            <ellipse cx="200" cy="320" rx="30" ry="15" fill="rgba(0,191,255,0.3)">
              <animate attributeName="opacity" values="0.1;0.4;0.1" dur="10s" repeatCount="indefinite"/>
            </ellipse>
            
            <!-- Title -->
            <text x="400" y="50" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">
              🌌 NAFEW AZIM - ML Engineer 🚀
            </text>
            
            <!-- Subtitle -->
            <text x="400" y="370" text-anchor="middle" fill="rgba(255,255,255,0.8)" font-family="Arial, sans-serif" font-size="14">
              Navigating the Universe of Data Science & Machine Learning
            </text>
          </svg>
          EOF

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
